// Kart başlıklarını union type olarak tanımla
export const CARD_TITLES = [
  'Cursor AI',
  'ChatGPT',
  'Claude',
  'Grok',
  'Muse',
  'Fooocus Colab',
  'Copilot',
] as const;

export type CardTitle = typeof CARD_TITLES[number];

// Örnek prompt verisi (EN/TR)
export const PROMPTS: Record<CardTitle, { en: { title: string; prompt: string }[]; tr: { title: string; prompt: string }[] }> = {
  'Cursor AI': {
    en: [
      { title: 'Code Review Checklist', prompt: 'Create a checklist for reviewing code for best practices.' },
      { title: 'Refactor for Readability', prompt: 'Refactor the code for readability and maintainability.' },
      { title: 'TypeScript Migration', prompt: 'Suggest a plan to migrate to TypeScript.' },
      { title: 'Code Quality Analysis', prompt: 'Evaluate code quality and suggest improvements.' },
      { title: 'SOLID Principles Review', prompt: 'Review code for SOLID principles compliance.' },
      { title: 'Performance Optimization', prompt: 'Identify and fix performance bottlenecks.' },
      { title: 'Reusability Assessment', prompt: 'Evaluate code reusability.' },
      { title: 'Code Standards Application', prompt: 'Check code against coding standards.' },
      { title: 'Testability Assessment', prompt: 'Analyze code testability.' },
      { title: 'Refactoring Suggestions', prompt: 'Suggest refactoring approaches.' },
      { title: 'State Management Analysis', prompt: 'Analyze state management in the code.' },
      { title: 'UI Behavior Analysis', prompt: 'Analyze UI behaviors and suggest improvements.' },
      { title: 'Security Vulnerability Detection', prompt: 'Identify and fix security vulnerabilities.' },
      { title: 'API Design Review', prompt: 'Review and suggest improvements for API design.' },
      { title: 'Database Schema Review', prompt: 'Review and suggest improvements for database schema.' },
      { title: 'System Architecture Review', prompt: 'Review and suggest improvements for system architecture.' },
      { title: 'Code Migration Planning', prompt: 'Plan the migration of code to a new framework.' },
      { title: 'Feature Implementation Review', prompt: 'Review and suggest improvements for feature implementation.' },
      { title: 'Bug Fix Analysis', prompt: 'Analyze and suggest fixes for bugs.' },
      { title: 'Code Generation Review', prompt: 'Review and suggest improvements for generated code.' },
      { title: 'Pattern Implementation Review', prompt: 'Review and suggest improvements for pattern implementation.' },
      { title: 'Code Review Process Review', prompt: 'Review and suggest improvements for code review process.' },
      { title: 'Testing Process Review', prompt: 'Review and suggest improvements for testing process.' },
      { title: 'Deployment Process Review', prompt: 'Review and suggest improvements for deployment process.' },
      { title: 'Maintenance Process Review', prompt: 'Review and suggest improvements for maintenance process.' },
      { title: 'Documentation Review', prompt: 'Review and suggest improvements for documentation.' },
      { title: 'Error Handling Review', prompt: 'Review and suggest improvements for error handling.' },
      { title: 'Logging Strategy Review', prompt: 'Review and suggest improvements for logging strategy.' },
      { title: 'Monitoring Setup Review', prompt: 'Review and suggest improvements for monitoring setup.' },
      { title: 'Security Setup Review', prompt: 'Review and suggest improvements for security setup.' },
      { title: 'Performance Monitoring Review', prompt: 'Review and suggest improvements for performance monitoring.' },
      { title: 'Code Metrics Review', prompt: 'Review and suggest improvements for code metrics.' },
      { title: 'Version Control Review', prompt: 'Review and suggest improvements for version control.' },
      { title: 'Dependency Management Review', prompt: 'Review and suggest improvements for dependency management.' },
      { title: 'Code Organization Review', prompt: 'Review and suggest improvements for code organization.' },
      { title: 'Error Prevention Review', prompt: 'Review and suggest improvements for error prevention.' },
      { title: 'Testing Coverage Review', prompt: 'Review and suggest improvements for testing coverage.' }
    ],
    tr: [
      { title: 'Kod İnceleme Kontrol Listesi', prompt: 'Kodu en iyi uygulamalar açısından incelemek için bir kontrol listesi oluştur.' },
      { title: 'Okunabilirlik için Yeniden Yapılandırma', prompt: 'Kodu okunabilirlik ve bakım yapılabilirlik için yeniden yapılandır.' },
      { title: 'TypeScript Geçişi', prompt: 'TypeScript\'e geçiş için bir plan öner.' },
      { title: 'Kod Kalite Analizi', prompt: 'Kod kalitesini değerlendir ve iyileştirmeler öner.' },
      { title: 'SOLID Prensipleri İncelemesi', prompt: 'Kodu SOLID prensiplerine uygunluk açısından incele.' },
      { title: 'Performans Optimizasyonu', prompt: 'Performans darboğazlarını belirle ve düzelt.' },
      { title: 'Yeniden Kullanılabilirlik Değerlendirmesi', prompt: 'Kodun yeniden kullanılabilirliğini değerlendir.' },
      { title: 'Kod Standartları Uygulaması', prompt: 'Kodu kodlama standartlarına göre kontrol et.' },
      { title: 'Test Edilebilirlik Değerlendirmesi', prompt: 'Kodun test edilebilirliğini analiz et.' },
      { title: 'Yeniden Yapılandırma Önerileri', prompt: 'Yeniden yapılandırma yaklaşımları öner.' },
      { title: 'Durum Yönetimi Analizi', prompt: 'Koddaki durum yönetimini analiz et.' },
      { title: 'UI Davranış Analizi', prompt: 'UI davranışlarını analiz et ve iyileştirmeler öner.' },
      { title: 'Güvenlik Açığı Tespiti', prompt: 'Güvenlik açıklarını belirle ve düzelt.' },
      { title: 'API Tasarım İncelemesi', prompt: 'API tasarımını incele ve iyileştirmeler öner.' },
      { title: 'Veritabanı Şeması İncelemesi', prompt: 'Veritabanı şemasını incele ve iyileştirmeler öner.' },
      { title: 'Sistem Mimarisi İncelemesi', prompt: 'Sistem mimarisini incele ve iyileştirmeler öner.' },
      { title: 'Kod Geçiş Planlaması', prompt: 'Kodun yeni bir framework\'e geçişini planla.' },
      { title: 'Özellik Uygulaması İncelemesi', prompt: 'Özellik uygulamasını incele ve iyileştirmeler öner.' },
      { title: 'Hata Düzeltme Analizi', prompt: 'Hataları analiz et ve düzeltmeler öner.' },
      { title: 'Kod Üretimi İncelemesi', prompt: 'Üretilen kodu incele ve iyileştirmeler öner.' },
      { title: 'Desen Uygulaması İncelemesi', prompt: 'Desen uygulamasını incele ve iyileştirmeler öner.' },
      { title: 'Kod İnceleme Süreci İncelemesi', prompt: 'Kod inceleme sürecini incele ve iyileştirmeler öner.' },
      { title: 'Test Süreci İncelemesi', prompt: 'Test sürecini incele ve iyileştirmeler öner.' },
      { title: 'Dağıtım Süreci İncelemesi', prompt: 'Dağıtım sürecini incele ve iyileştirmeler öner.' },
      { title: 'Bakım Süreci İncelemesi', prompt: 'Bakım sürecini incele ve iyileştirmeler öner.' },
      { title: 'Dokümantasyon İncelemesi', prompt: 'Dokümantasyonu incele ve iyileştirmeler öner.' },
      { title: 'Hata Yönetimi İncelemesi', prompt: 'Hata yönetimini incele ve iyileştirmeler öner.' },
      { title: 'Günlük Kaydı Stratejisi İncelemesi', prompt: 'Günlük kaydı stratejisini incele ve iyileştirmeler öner.' },
      { title: 'İzleme Kurulumu İncelemesi', prompt: 'İzleme kurulumunu incele ve iyileştirmeler öner.' },
      { title: 'Güvenlik Kurulumu İncelemesi', prompt: 'Güvenlik kurulumunu incele ve iyileştirmeler öner.' },
      { title: 'Performans İzleme İncelemesi', prompt: 'Performans izlemeyi incele ve iyileştirmeler öner.' },
      { title: 'Kod Metrikleri İncelemesi', prompt: 'Kod metriklerini incele ve iyileştirmeler öner.' },
      { title: 'Sürüm Kontrolü İncelemesi', prompt: 'Sürüm kontrolünü incele ve iyileştirmeler öner.' },
      { title: 'Bağımlılık Yönetimi İncelemesi', prompt: 'Bağımlılık yönetimini incele ve iyileştirmeler öner.' },
      { title: 'Kod Organizasyonu İncelemesi', prompt: 'Kod organizasyonunu incele ve iyileştirmeler öner.' },
      { title: 'Hata Önleme İncelemesi', prompt: 'Hata önlemeyi incele ve iyileştirmeler öner.' },
      { title: 'Test Kapsamı İncelemesi', prompt: 'Test kapsamını incele ve iyileştirmeler öner.' }
    ]
  },
  'ChatGPT': {
    en: [
      { title: 'Patent Idea Validation', prompt: 'Validate this patent idea and suggest improvements.' },
      { title: 'Technical Documentation', prompt: 'Create technical documentation for this feature.' },
      { title: 'Code Review Automation', prompt: 'Automate the code review process for this project.' },
      { title: 'Code Quality Standards', prompt: 'Apply code quality standards to this codebase.' },
      { title: 'SOLID Principles Validation', prompt: 'Validate the code\'s compliance with SOLID principles.' },
      { title: 'Component Pattern Analysis', prompt: 'Analyze component patterns in this codebase.' },
      { title: 'Code Optimization', prompt: 'Optimize this code for better performance.' },
      { title: 'Performance Analysis', prompt: 'Analyze the performance of this code.' },
      { title: 'Readability Improvement', prompt: 'Improve code readability.' },
      { title: 'Implementation Comparison', prompt: 'Compare different implementations.' },
      { title: 'Context-Aware Completion', prompt: 'Complete the code with context-aware suggestions.' },
      { title: 'Micro Optimizations', prompt: 'Suggest micro optimizations for the code.' },
      { title: 'Pattern Recognition', prompt: 'Recognize patterns in the code.' },
      { title: 'Code Consistency', prompt: 'Ensure code consistency.' },
      { title: 'Code Review Checklist', prompt: 'Create a checklist for reviewing code.' },
      { title: 'Refactoring for Readability', prompt: 'Refactor the code for readability and maintainability.' },
      { title: 'TypeScript Migration', prompt: 'Suggest a plan to migrate to TypeScript.' },
      { title: 'Code Quality Analysis', prompt: 'Evaluate code quality and suggest improvements.' },
      { title: 'SOLID Principles Review', prompt: 'Review code for SOLID principles compliance.' },
      { title: 'Performance Optimization', prompt: 'Identify and fix performance bottlenecks.' },
      { title: 'Reusability Assessment', prompt: 'Evaluate code reusability.' },
      { title: 'Code Standards Application', prompt: 'Check code against coding standards.' },
      { title: 'Testability Assessment', prompt: 'Analyze code testability.' },
      { title: 'Refactoring Suggestions', prompt: 'Suggest refactoring approaches.' },
      { title: 'State Management Analysis', prompt: 'Analyze state management in the code.' },
      { title: 'UI Behavior Analysis', prompt: 'Analyze UI behaviors and suggest improvements.' },
      { title: 'Security Vulnerability Detection', prompt: 'Identify and fix security vulnerabilities.' },
      { title: 'API Design Review', prompt: 'Review and suggest improvements for API design.' },
      { title: 'Database Schema Review', prompt: 'Review and suggest improvements for database schema.' },
      { title: 'System Architecture Review', prompt: 'Review and suggest improvements for system architecture.' },
      { title: 'Code Migration Planning', prompt: 'Plan the migration of code to a new framework.' },
      { title: 'Feature Implementation Review', prompt: 'Review and suggest improvements for feature implementation.' },
      { title: 'Bug Fix Analysis', prompt: 'Analyze and suggest fixes for bugs.' },
      { title: 'Code Generation Review', prompt: 'Review and suggest improvements for generated code.' },
      { title: 'Pattern Implementation Review', prompt: 'Review and suggest improvements for pattern implementation.' },
      { title: 'Code Review Process Review', prompt: 'Review and suggest improvements for code review process.' },
      { title: 'Testing Process Review', prompt: 'Review and suggest improvements for testing process.' },
      { title: 'Deployment Process Review', prompt: 'Review and suggest improvements for deployment process.' },
      { title: 'Maintenance Process Review', prompt: 'Review and suggest improvements for maintenance process.' },
      { title: 'Documentation Review', prompt: 'Review and suggest improvements for documentation.' },
      { title: 'Error Handling Review', prompt: 'Review and suggest improvements for error handling.' },
      { title: 'Logging Strategy Review', prompt: 'Review and suggest improvements for logging strategy.' },
      { title: 'Monitoring Setup Review', prompt: 'Review and suggest improvements for monitoring setup.' },
      { title: 'Security Setup Review', prompt: 'Review and suggest improvements for security setup.' },
      { title: 'Performance Monitoring Review', prompt: 'Review and suggest improvements for performance monitoring.' },
      { title: 'Code Metrics Review', prompt: 'Review and suggest improvements for code metrics.' },
      { title: 'Version Control Review', prompt: 'Review and suggest improvements for version control.' },
      { title: 'Dependency Management Review', prompt: 'Review and suggest improvements for dependency management.' },
      { title: 'Code Organization Review', prompt: 'Review and suggest improvements for code organization.' },
      { title: 'Error Prevention Review', prompt: 'Review and suggest improvements for error prevention.' },
      { title: 'Testing Coverage Review', prompt: 'Review and suggest improvements for testing coverage.' }
    ],
    tr: [
      { title: 'Patent Fikri Doğrulama', prompt: 'Bu patent fikrini doğrula ve iyileştirmeler öner.' },
      { title: 'Teknik Dokümantasyon', prompt: 'Bu özellik için teknik dokümantasyon oluştur.' },
      { title: 'Kod İnceleme Otomasyonu', prompt: 'Bu proje için kod inceleme sürecini otomatikleştir.' },
      { title: 'Kod Kalitesi Standartları', prompt: 'Bu kod tabanına kod kalitesi standartlarını uygula.' },
      { title: 'SOLID Prensipleri Doğrulama', prompt: 'Kodun SOLID prensiplerine uygunluğunu doğrula.' },
      { title: 'Bileşen Deseni Analizi', prompt: 'Bu kod tabanındaki bileşen desenlerini analiz et.' },
      { title: 'Kod Optimizasyonu', prompt: 'Bu kodu daha iyi performans için optimize et.' },
      { title: 'Performans Analizi', prompt: 'Bu kodun performansını analiz et.' },
      { title: 'Okunabilirlik İyileştirme', prompt: 'Kodun okunabilirliğini artır.' },
      { title: 'Uygulama Karşılaştırması', prompt: 'Farklı uygulamaları karşılaştır.' },
      { title: 'Bağlam Duyarlı Tamamlama', prompt: 'Kodu bağlam duyarlı önerilerle tamamla.' },
      { title: 'Mikro Optimizasyonlar', prompt: 'Kod için mikro optimizasyonlar öner.' },
      { title: 'Desen Tanıma', prompt: 'Koddaki desenleri tanı.' },
      { title: 'Kod Tutarlılığı', prompt: 'Kodun tutarlılığını sağla.' },
      { title: 'Kod İnceleme Kontrol Listesi', prompt: 'Kodu incelemek için bir kontrol listesi oluştur.' },
      { title: 'Okunabilirlik için Yeniden Yapılandırma', prompt: 'Kodu okunabilirlik ve bakım yapılabilirlik için yeniden yapılandır.' },
      { title: 'TypeScript Geçişi', prompt: 'TypeScript\'e geçiş için bir plan öner.' },
      { title: 'Kod Kalite Analizi', prompt: 'Kod kalitesini değerlendir ve iyileştirmeler öner.' },
      { title: 'SOLID Prensipleri İncelemesi', prompt: 'Kodu SOLID prensiplerine uygunluk açısından incele.' },
      { title: 'Performans Optimizasyonu', prompt: 'Performans darboğazlarını belirle ve düzelt.' },
      { title: 'Yeniden Kullanılabilirlik Değerlendirmesi', prompt: 'Kodun yeniden kullanılabilirliğini değerlendir.' },
      { title: 'Kod Standartları Uygulaması', prompt: 'Kodu kodlama standartlarına göre kontrol et.' },
      { title: 'Test Edilebilirlik Değerlendirmesi', prompt: 'Kodun test edilebilirliğini analiz et.' },
      { title: 'Yeniden Yapılandırma Önerileri', prompt: 'Koddaki karmaşık veya tekrarlayan bölümleri belirle ve yeniden yapılandırma önerileri sun.' },
      { title: 'Durum Yönetimi Analizi', prompt: 'React kodundaki potansiyel durum yönetimi sorunlarını bul ve çözümler öner.' },
      { title: 'UI Davranış Analizi', prompt: 'UI davranışlarını analiz et ve kullanıcı deneyimini geliştirmek için öneriler sun.' },
      { title: 'Güvenlik Açığı Tespiti', prompt: 'Koddaki olası güvenlik açıklarını tespit et ve nasıl önleneceğini açıkla.' },
      { title: 'API Tasarım İncelemesi', prompt: 'API tasarımını incele ve iyileştirmeler öner.' },
      { title: 'Veritabanı Şeması İncelemesi', prompt: 'Veritabanı şemasını incele ve iyileştirmeler öner.' },
      { title: 'Sistem Mimarisi İncelemesi', prompt: 'Sistem mimarisini incele ve iyileştirmeler öner.' },
      { title: 'Kod Geçiş Planlaması', prompt: 'Kodun yeni bir framework\'e geçişini planla.' },
      { title: 'Özellik Uygulaması İncelemesi', prompt: 'Özellik uygulamasını incele ve iyileştirmeler öner.' },
      { title: 'Hata Düzeltme Analizi', prompt: 'Hataları analiz et ve düzeltmeler öner.' },
      { title: 'Kod Üretimi İncelemesi', prompt: 'Üretilen kodu incele ve iyileştirmeler öner.' },
      { title: 'Desen Uygulaması İncelemesi', prompt: 'Desen uygulamasını incele ve iyileştirmeler öner.' },
      { title: 'Kod İnceleme Süreci İncelemesi', prompt: 'Kod inceleme sürecini incele ve iyileştirmeler öner.' },
      { title: 'Test Süreci İncelemesi', prompt: 'Test sürecini incele ve iyileştirmeler öner.' },
      { title: 'Dağıtım Süreci İncelemesi', prompt: 'Dağıtım sürecini incele ve iyileştirmeler öner.' },
      { title: 'Bakım Süreci İncelemesi', prompt: 'Bakım sürecini incele ve iyileştirmeler öner.' },
      { title: 'Dokümantasyon İncelemesi', prompt: 'Dokümantasyonu incele ve iyileştirmeler öner.' },
      { title: 'Hata Yönetimi İncelemesi', prompt: 'Hata yönetimini incele ve iyileştirmeler öner.' },
      { title: 'Toplantı Notları Özeti', prompt: 'Bu toplantı tutanağından ana noktaları özetle.' },
      { title: 'Yol Haritası Oluşturma', prompt: 'Bu ürün için bir geliştirme yol haritası oluştur.' },
      { title: 'Paydaş İletişimi', prompt: 'Proje paydaşları için bir güncelleme e-postası taslağı hazırla.' },
      { title: 'Özellik Önceliklendirme', prompt: 'Bir sonraki sürüm için özellikleri önceliklendir.' }
    ]
  },
  'Claude': {
    en: [
      { title: 'Project Breakdown', prompt: 'Break down this project into actionable tasks and edge cases.' },
      { title: 'Scalable Component Library Structure', prompt: 'Plan a scalable component library structure.' },
      { title: 'Legal Document Summary', prompt: 'Summarize the following legal document in simple terms.' },
      { title: 'Privacy Policy Draft', prompt: 'Draft a privacy policy for a SaaS web application.' },
      { title: 'Contract Risk Analysis', prompt: 'Identify potential risks in the following contract.' },
      { title: 'Project Planning', prompt: 'Plan and organize a project to achieve specific goals.' },
      { title: 'Task Breakdown', prompt: 'Break down this project into tasks.' },
      { title: 'Edge Case Analysis', prompt: 'Analyze potential edge cases in the project.' },
      { title: 'Refactoring Strategies', prompt: 'Develop refactoring strategies for the project.' },
      { title: 'Component Library Design', prompt: 'Design a component library for the project.' },
      { title: 'System Architecture Planning', prompt: 'Plan the system architecture for the project.' },
      { title: 'Component Design', prompt: 'Design a component for the project.' },
      { title: 'Visual Style Consistency', prompt: 'Ensure visual style consistency across the project.' },
      { title: 'Scene Composition', prompt: 'Compose a scene for the project.' },
      { title: 'Interactive Design', prompt: 'Design interactive elements for the project.' },
      { title: 'Asset Creation', prompt: 'Create assets for the project.' },
      { title: 'Game Prototyping', prompt: 'Create a game prototype for the project.' },
      { title: 'Patent Analysis', prompt: 'Analyze potential patents for the project.' },
      { title: 'Technical Documentation', prompt: 'Document the technical aspects of the project.' },
      { title: 'Code Review', prompt: 'Review the code for the project.' },
      { title: 'Import Structure Analysis', prompt: 'Analyze the import structure of the project.' },
      { title: 'Patent Idea Validation', prompt: 'Validate a patent idea for the project.' },
      { title: 'Technical Writing', prompt: 'Write technical documentation for the project.' },
      { title: 'Code Review Automation', prompt: 'Automate the code review process for the project.' },
      { title: 'Code Quality Standards', prompt: 'Apply code quality standards to the project.' },
      { title: 'SOLID Principles Validation', prompt: 'Validate the project\'s compliance with SOLID principles.' },
      { title: 'Component Pattern Analysis', prompt: 'Analyze component patterns in the project.' },
      { title: 'Code Optimization', prompt: 'Optimize the code for the project.' },
      { title: 'Performance Analysis', prompt: 'Analyze the performance of the project.' },
      { title: 'Readability Improvement', prompt: 'Improve code readability for the project.' },
      { title: 'Implementation Comparison', prompt: 'Compare different implementations for the project.' },
      { title: 'Context-Aware Completion', prompt: 'Complete the code with context-aware suggestions.' },
      { title: 'Micro Optimizations', prompt: 'Suggest micro optimizations for the code.' },
      { title: 'Pattern Recognition', prompt: 'Recognize patterns in the code for the project.' },
      { title: 'Code Consistency', prompt: 'Ensure code consistency for the project.' },
      { title: 'Meeting Notes Summary', prompt: 'Summarize the key points from this meeting transcript.' },
      { title: 'Roadmap Creation', prompt: 'Create a development roadmap for this product.' },
      { title: 'Stakeholder Communication', prompt: 'Draft an update email for project stakeholders.' },
      { title: 'Feature Prioritization', prompt: 'Prioritize features for the next release.' }
    ],
    tr: [
      { title: 'Yasal Belge Özeti', prompt: 'Aşağıdaki yasal belgeyi basit bir dille özetle.' },
      { title: 'Gizlilik Politikası Taslağı', prompt: 'SaaS web uygulaması için bir gizlilik politikası taslağı hazırla.' },
      { title: 'Sözleşme Risk Analizi', prompt: 'Aşağıdaki sözleşmedeki potansiyel riskleri belirle.' },
      { title: 'Proje Planlaması', prompt: 'Belirli hedeflere ulaşmak için bir projeyi planla ve organize et.' },
      { title: 'Görev Ayrıştırma', prompt: 'Bu projeyi görevlere ayır.' },
      { title: 'Sınır Durumu Analizi', prompt: 'Projedeki potansiyel sınır durumlarını analiz et.' },
      { title: 'Yeniden Yapılandırma Stratejileri', prompt: 'Proje için yeniden yapılandırma stratejileri geliştir.' },
      { title: 'Bileşen Kütüphanesi Tasarımı', prompt: 'Proje için bir bileşen kütüphanesi tasarla.' },
      { title: 'Sistem Mimarisi Planlaması', prompt: 'Proje için sistem mimarisini planla.' },
      { title: 'Bileşen Tasarımı', prompt: 'Proje için bir bileşen tasarla.' },
      { title: 'Görsel Stil Tutarlılığı', prompt: 'Proje genelinde görsel stil tutarlılığını sağla.' },
      { title: 'Sahne Kompozisyonu', prompt: 'Proje için bir sahne kompoze et.' },
      { title: 'Etkileşimli Tasarım', prompt: 'Proje için etkileşimli elementler tasarla.' },
      { title: 'Varlık Oluşturma', prompt: 'Proje için varlıklar oluştur.' },
      { title: 'Oyun Prototipleme', prompt: 'Proje için bir oyun prototipi oluştur.' },
      { title: 'Patent Analizi', prompt: 'Proje için potansiyel patentleri analiz et.' },
      { title: 'Teknik Dokümantasyon', prompt: 'Projenin teknik yönlerini dokümante et.' },
      { title: 'Kod İncelemesi', prompt: 'Proje için kodu incele.' },
      { title: 'İçe Aktarma Yapısı Analizi', prompt: 'Proje için içe aktarma yapısını analiz et.' },
      { title: 'Patent Fikri Doğrulama', prompt: 'Proje için bir patent fikrini doğrula.' },
      { title: 'Teknik Yazım', prompt: 'Proje için teknik dokümantasyon yaz.' },
      { title: 'Kod İnceleme Otomasyonu', prompt: 'Proje için kod inceleme sürecini otomatikleştir.' },
      { title: 'Kod Kalitesi Uygulaması', prompt: 'Proje için kod kalite standartlarını uygula.' },
      { title: 'SOLID Prensibi Doğrulama', prompt: 'Projenin SOLID prensiplerine uygunluğunu doğrula.' },
      { title: 'Bileşen Deseni Analizi', prompt: 'Projedeki bileşen desenlerini analiz et.' },
      { title: 'Kod Optimizasyonu', prompt: 'Proje için kodu optimize et.' },
      { title: 'Performans Analizi', prompt: 'Projenin performansını analiz et.' },
      { title: 'Okunabilirlik İyileştirme', prompt: 'Proje için kodun okunabilirliğini artır.' },
      { title: 'Uygulama Karşılaştırması', prompt: 'Proje için farklı uygulamaları karşılaştır.' },
      { title: 'Bağlam Duyarlı Tamamlama', prompt: 'Kodu bağlam duyarlı önerilerle tamamla.' },
      { title: 'Mikro Optimizasyonlar', prompt: 'Kod için mikro optimizasyonlar öner.' },
      { title: 'Desen Tanıma', prompt: 'Proje için koddaki desenleri tanı.' },
      { title: 'Kod Tutarlılığı', prompt: 'Proje için kodun tutarlılığını sağla.' },
      { title: 'Kod İnceleme Kontrol Listesi', prompt: 'React kodu için en iyi uygulamaları inceleyen bir kontrol listesi oluştur.' },
      { title: 'Okunabilirlik için Yeniden Yapılandırma', prompt: 'Aşağıdaki kodu okunabilirlik ve bakım yapılabilirlik için yeniden yapılandır.' },
      { title: 'TypeScript Geçişi', prompt: 'Bu JavaScript kod tabanını TypeScript\'e dönüştürmek için bir geçiş planı öner.' },
      { title: 'Kod Kalite Analizi', prompt: 'Aşağıdaki kodun okunabilirliğini ve bakım yapılabilirliğini değerlendir. İyileştirme için detaylı öneriler sun.' },
      { title: 'SOLID Prensipleri İncelemesi', prompt: 'Bu React bileşeni SOLID prensiplerine uyuyor mu? Detaylı bir analiz yap ve gerekirse örnek kodla yeniden yapılandır.' },
      { title: 'Performans Optimizasyonu', prompt: 'Koddaki performans darboğazlarını belirle ve iyileştirmeler öner.' },
      { title: 'Yeniden Kullanılabilirlik Değerlendirmesi', prompt: 'Aşağıdaki bileşenin farklı projelerde yeniden kullanılabilirliğini değerlendir.' },
      { title: 'Kod Standartları Uygulaması', prompt: 'Kodun şirket kodlama standartlarına uygunluğunu kontrol et ve eksiklikleri vurgula.' },
      { title: 'Test Edilebilirlik Değerlendirmesi', prompt: 'Kodun test edilebilirliğini analiz et ve eksik test senaryolarını öner.' },
      { title: 'Yeniden Yapılandırma Önerileri', prompt: 'Koddaki karmaşık veya tekrarlayan bölümleri belirle ve yeniden yapılandırma önerileri sun.' },
      { title: 'Durum Yönetimi Analizi', prompt: 'React kodundaki potansiyel durum yönetimi sorunlarını bul ve çözümler öner.' },
      { title: 'UI Davranış Analizi', prompt: 'UI davranışlarını analiz et ve kullanıcı deneyimini geliştirmek için öneriler sun.' },
      { title: 'Güvenlik Açığı Tespiti', prompt: 'Koddaki olası güvenlik açıklarını tespit et ve nasıl önleneceğini açıkla.' },
      { title: 'Toplantı Notları Özeti', prompt: 'Bu toplantı tutanağından ana noktaları özetle.' },
      { title: 'Yol Haritası Oluşturma', prompt: 'Bu ürün için bir geliştirme yol haritası oluştur.' },
      { title: 'Paydaş İletişimi', prompt: 'Proje paydaşları için bir güncelleme e-postası taslağı hazırla.' },
      { title: 'Özellik Önceliklendirme', prompt: 'Bir sonraki sürüm için özellikleri önceliklendir.' }
    ]
  },
  'Grok': {
    en: [
      { title: 'Explain AI Concept', prompt: 'Explain a complex AI concept in simple terms.' },
      { title: 'Data Visualization', prompt: 'Suggest ways to visualize this dataset.' },
      { title: 'Python Code Debugging', prompt: 'Debug this Python code and explain the issues.' },
      { title: 'Logic Validation', prompt: 'Validate the logic in this code snippet.' },
      { title: 'Code Optimization', prompt: 'Optimize this code for better performance.' },
      { title: 'Algorithm Analysis', prompt: 'Analyze the efficiency of this algorithm.' },
      { title: 'Data Structure Selection', prompt: 'Suggest the best data structure for this use case.' },
      { title: 'Error Handling', prompt: 'Improve error handling in this code.' },
      { title: 'Code Documentation', prompt: 'Generate documentation for this code.' },
      { title: 'Testing Strategy', prompt: 'Suggest a testing strategy for this feature.' },
      { title: 'Code Review', prompt: 'Review this code for best practices.' },
      { title: 'Performance Analysis', prompt: 'Analyze the performance of this code.' },
      { title: 'Security Assessment', prompt: 'Assess the security of this code.' },
      { title: 'Scalability Analysis', prompt: 'Analyze the scalability of this solution.' },
      { title: 'Maintainability Review', prompt: 'Review the maintainability of this code.' },
      { title: 'Code Refactoring', prompt: 'Suggest refactoring for this code.' },
      { title: 'API Design', prompt: 'Design an API for this feature.' },
      { title: 'Database Schema', prompt: 'Design a database schema for this application.' },
      { title: 'System Architecture', prompt: 'Suggest a system architecture for this project.' },
      { title: 'Code Migration', prompt: 'Plan the migration of this code to a new framework.' },
      { title: 'Feature Implementation', prompt: 'Suggest an implementation for this feature.' },
      { title: 'Bug Fix', prompt: 'Suggest a fix for this bug.' },
      { title: 'Code Generation', prompt: 'Generate code for this requirement.' },
      { title: 'Pattern Implementation', prompt: 'Implement a design pattern for this scenario.' },
      { title: 'Code Review Checklist', prompt: 'Create a checklist for reviewing this code.' },
      { title: 'Performance Optimization', prompt: 'Suggest optimizations for this code.' },
      { title: 'Security Enhancement', prompt: 'Suggest security enhancements for this code.' },
      { title: 'Code Quality', prompt: 'Assess the quality of this code.' },
      { title: 'Best Practices', prompt: 'Suggest best practices for this code.' },
      { title: 'Code Standards', prompt: 'Review this code against coding standards.' },
      { title: 'Documentation Review', prompt: 'Review the documentation for this code.' },
      { title: 'Testing Coverage', prompt: 'Suggest test cases for this code.' },
      { title: 'Error Prevention', prompt: 'Suggest ways to prevent errors in this code.' },
      { title: 'Code Organization', prompt: 'Suggest ways to organize this code.' },
      { title: 'Dependency Management', prompt: 'Suggest ways to manage dependencies in this project.' },
      { title: 'Version Control', prompt: 'Suggest a version control strategy for this project.' },
      { title: 'Deployment Strategy', prompt: 'Suggest a deployment strategy for this application.' },
      { title: 'Monitoring Setup', prompt: 'Suggest a monitoring setup for this application.' },
      { title: 'Logging Strategy', prompt: 'Suggest a logging strategy for this application.' },
      { title: 'Error Tracking', prompt: 'Suggest an error tracking solution for this application.' },
      { title: 'Performance Monitoring', prompt: 'Suggest a performance monitoring solution.' },
      { title: 'Security Monitoring', prompt: 'Suggest a security monitoring solution.' },
      { title: 'Code Metrics', prompt: 'Suggest code metrics for this project.' },
      { title: 'Code Review Process', prompt: 'Suggest a code review process for this project.' },
      { title: 'Testing Process', prompt: 'Suggest a testing process for this project.' },
      { title: 'Deployment Process', prompt: 'Suggest a deployment process for this project.' },
      { title: 'Maintenance Process', prompt: 'Suggest a maintenance process for this project.' }
    ],
    tr: [
      { title: 'Yapay Zeka Kavramını Açıkla', prompt: 'Karmaşık bir yapay zeka kavramını basit terimlerle açıkla.' },
      { title: 'Veri Görselleştirme', prompt: 'Bu veri setini görselleştirmek için yollar öner.' },
      { title: 'Python Kodu Hata Ayıklama', prompt: 'Bu Python kodunu hata ayıkla ve sorunları açıkla.' },
      { title: 'Mantık Doğrulama', prompt: 'Bu kod parçasındaki mantığı doğrula.' },
      { title: 'Kod Optimizasyonu', prompt: 'Bu kodu daha iyi performans için optimize et.' },
      { title: 'Algoritma Analizi', prompt: 'Bu algoritmanın verimliliğini analiz et.' },
      { title: 'Veri Yapısı Seçimi', prompt: 'Bu kullanım durumu için en iyi veri yapısını öner.' },
      { title: 'Hata Yönetimi', prompt: 'Bu koddaki hata yönetimini iyileştir.' },
      { title: 'Kod Dokümantasyonu', prompt: 'Bu kod için dokümantasyon oluştur.' },
      { title: 'Test Stratejisi', prompt: 'Bu özellik için bir test stratejisi öner.' },
      { title: 'Kod İncelemesi', prompt: 'Bu kodu en iyi uygulamalar açısından incele.' },
      { title: 'Performans Analizi', prompt: 'Bu kodun performansını analiz et.' },
      { title: 'Güvenlik Değerlendirmesi', prompt: 'Bu kodun güvenliğini değerlendir.' },
      { title: 'Ölçeklenebilirlik Analizi', prompt: 'Bu çözümün ölçeklenebilirliğini analiz et.' },
      { title: 'Bakım Yapılabilirlik İncelemesi', prompt: 'Bu kodun bakım yapılabilirliğini incele.' },
      { title: 'Kod Yeniden Yapılandırma', prompt: 'Bu kod için yeniden yapılandırma öner.' },
      { title: 'API Tasarımı', prompt: 'Bu özellik için bir API tasarla.' },
      { title: 'Veritabanı Şeması', prompt: 'Bu uygulama için bir veritabanı şeması tasarla.' },
      { title: 'Sistem Mimarisi', prompt: 'Bu proje için bir sistem mimarisi öner.' },
      { title: 'Kod Geçişi', prompt: 'Bu kodun yeni bir framework\'e geçişini planla.' },
      { title: 'Özellik Uygulaması', prompt: 'Bu özellik için bir uygulama öner.' },
      { title: 'Hata Düzeltme', prompt: 'Bu hata için bir düzeltme öner.' },
      { title: 'Kod Üretimi', prompt: 'Bu gereksinim için kod üret.' },
      { title: 'Desen Uygulaması', prompt: 'Bu senaryo için bir tasarım deseni uygula.' },
      { title: 'Kod İnceleme Kontrol Listesi', prompt: 'Bu kodu incelemek için bir kontrol listesi oluştur.' },
      { title: 'Performans Optimizasyonu', prompt: 'Bu kod için optimizasyonlar öner.' },
      { title: 'Güvenlik İyileştirmesi', prompt: 'Bu kod için güvenlik iyileştirmeleri öner.' },
      { title: 'Kod Kalitesi', prompt: 'Bu kodun kalitesini değerlendir.' },
      { title: 'En İyi Uygulamalar', prompt: 'Bu kod için en iyi uygulamaları öner.' },
      { title: 'Kod Standartları', prompt: 'Bu kodu kodlama standartlarına göre incele.' },
      { title: 'Dokümantasyon İncelemesi', prompt: 'Bu kodun dokümantasyonunu incele.' },
      { title: 'Test Kapsamı', prompt: 'Bu kod için test senaryoları öner.' },
      { title: 'Hata Önleme', prompt: 'Bu koddaki hataları önlemek için yollar öner.' },
      { title: 'Kod Organizasyonu', prompt: 'Bu kodu organize etmek için yollar öner.' },
      { title: 'Bağımlılık Yönetimi', prompt: 'Bu projedeki bağımlılıkları yönetmek için yollar öner.' },
      { title: 'Sürüm Kontrolü', prompt: 'Bu proje için bir sürüm kontrol stratejisi öner.' },
      { title: 'Dağıtım Stratejisi', prompt: 'Bu uygulama için bir dağıtım stratejisi öner.' },
      { title: 'İzleme Kurulumu', prompt: 'Bu uygulama için bir izleme kurulumu öner.' },
      { title: 'Günlük Kaydı Stratejisi', prompt: 'Bu uygulama için bir günlük kaydı stratejisi öner.' },
      { title: 'Hata İzleme', prompt: 'Bu uygulama için bir hata izleme çözümü öner.' },
      { title: 'Performans İzleme', prompt: 'Bir performans izleme çözümü öner.' },
      { title: 'Güvenlik İzleme', prompt: 'Bir güvenlik izleme çözümü öner.' },
      { title: 'Kod Metrikleri', prompt: 'Bu proje için kod metrikleri öner.' },
      { title: 'Kod İnceleme Süreci', prompt: 'Bu proje için bir kod inceleme süreci öner.' },
      { title: 'Test Süreci', prompt: 'Bu proje için bir test süreci öner.' },
      { title: 'Dağıtım Süreci', prompt: 'Bu proje için bir dağıtım süreci öner.' },
      { title: 'Bakım Süreci', prompt: 'Bu proje için bir bakım süreci öner.' }
    ]
  },
  'Muse': {
    en: [
      { title: 'Create Album Cover', prompt: 'Create a unique album cover for a music artist.' },
      { title: 'Tech Event Poster', prompt: 'Design a poster for a technology conference.' },
      { title: 'Children\'s Book Illustration', prompt: 'Create an illustration for a children\'s book.' },
      { title: 'Game Character Design', prompt: 'Design a character for a video game.' },
      { title: 'Product Packaging', prompt: 'Create packaging design for a new product.' },
      { title: 'Social Media Banner', prompt: 'Design a banner for social media marketing.' },
      { title: 'Logo Design', prompt: 'Create a logo for a new brand.' },
      { title: 'Book Cover', prompt: 'Design a cover for a novel.' },
      { title: 'Movie Poster', prompt: 'Create a poster for a movie.' },
      { title: 'Website Banner', prompt: 'Design a banner for a website.' },
      { title: 'App Icon', prompt: 'Create an icon for a mobile app.' },
      { title: 'Infographic', prompt: 'Design an infographic about a topic.' },
      { title: 'Comic Strip', prompt: 'Create a comic strip panel.' },
      { title: 'Character Concept', prompt: 'Design a character concept art.' },
      { title: 'Environment Design', prompt: 'Create an environment design for a game.' },
      { title: 'Product Mockup', prompt: 'Create a mockup for a product.' },
      { title: 'Event Flyer', prompt: 'Design a flyer for an event.' },
      { title: 'Brand Identity', prompt: 'Create a brand identity design.' },
      { title: 'UI Kit', prompt: 'Design a UI kit for an application.' },
      { title: 'Icon Set', prompt: 'Create a set of icons for a project.' },
      { title: 'Social Media Post', prompt: 'Design a post for social media.' },
      { title: 'Newsletter Header', prompt: 'Create a header for a newsletter.' },
      { title: 'Presentation Slide', prompt: 'Design a slide for a presentation.' },
      { title: 'Email Template', prompt: 'Create a template for email marketing.' },
      { title: 'Brochure Design', prompt: 'Design a brochure for a business.' },
      { title: 'Menu Design', prompt: 'Create a design for a restaurant menu.' },
      { title: 'Business Card', prompt: 'Design a business card.' },
      { title: 'Invitation Card', prompt: 'Create an invitation card design.' },
      { title: 'Calendar Design', prompt: 'Design a calendar for a brand.' },
      { title: 'T-shirt Design', prompt: 'Create a design for a T-shirt.' },
      { title: 'Wallpaper Design', prompt: 'Design a wallpaper for devices.' },
      { title: 'Sticker Design', prompt: 'Create a design for stickers.' },
      { title: 'Badge Design', prompt: 'Design a badge for an event.' },
      { title: 'Certificate Design', prompt: 'Create a design for a certificate.' },
      { title: 'Label Design', prompt: 'Design a label for a product.' },
      { title: 'Packaging Mockup', prompt: 'Create a mockup for product packaging.' },
      { title: 'Social Media Story', prompt: 'Design a story for social media.' },
      { title: 'Profile Picture', prompt: 'Create a profile picture design.' },
      { title: 'Cover Photo', prompt: 'Design a cover photo for social media.' },
      { title: 'Poster Series', prompt: 'Create a series of related posters.' },
      { title: 'Character Sheet', prompt: 'Design a character sheet for animation.' },
      { title: 'Environment Concept', prompt: 'Create a concept for an environment.' },
      { title: 'Vehicle Design', prompt: 'Design a vehicle for a game.' },
      { title: 'Creature Design', prompt: 'Create a design for a creature.' },
      { title: 'Weapon Design', prompt: 'Design a weapon for a game.' },
      { title: 'Prop Design', prompt: 'Create a design for a prop.' },
      { title: 'Scene Composition', prompt: 'Design a composition for a scene.' },
      { title: 'Lighting Setup', prompt: 'Create a lighting setup for a scene.' },
      { title: 'Color Palette', prompt: 'Design a color palette for a project.' },
      { title: 'Typography Design', prompt: 'Create a typography design.' },
      { title: 'Pattern Design', prompt: 'Design a pattern for a product.' }
    ],
    tr: [
      { title: 'Albüm Kapağı Oluştur', prompt: 'Bir müzik sanatçısı için özgün bir albüm kapağı oluştur.' },
      { title: 'Teknoloji Etkinliği Posteri', prompt: 'Teknoloji konferansı için bir poster tasarla.' },
      { title: 'Çocuk Kitabı İllüstrasyonu', prompt: 'Çocuk kitabı için bir illüstrasyon oluştur.' },
      { title: 'Oyun Karakteri Tasarımı', prompt: 'Video oyunu için bir karakter tasarla.' },
      { title: 'Ürün Ambalajı', prompt: 'Yeni bir ürün için ambalaj tasarımı oluştur.' },
      { title: 'Sosyal Medya Banner\'ı', prompt: 'Sosyal medya pazarlaması için bir banner tasarla.' },
      { title: 'Logo Tasarımı', prompt: 'Yeni bir marka için logo oluştur.' },
      { title: 'Kitap Kapağı', prompt: 'Bir roman için kapak tasarla.' },
      { title: 'Film Posteri', prompt: 'Bir film için poster oluştur.' },
      { title: 'Website Banner\'ı', prompt: 'Bir website için banner tasarla.' },
      { title: 'Uygulama İkonu', prompt: 'Mobil uygulama için bir ikon oluştur.' },
      { title: 'İnfografik', prompt: 'Bir konu hakkında infografik tasarla.' },
      { title: 'Çizgi Roman', prompt: 'Bir çizgi roman paneli oluştur.' },
      { title: 'Karakter Konsepti', prompt: 'Bir karakter konsept sanatı tasarla.' },
      { title: 'Ortam Tasarımı', prompt: 'Bir oyun için ortam tasarımı oluştur.' },
      { title: 'Ürün Mockup\'ı', prompt: 'Bir ürün için mockup oluştur.' },
      { title: 'Etkinlik Flyer\'ı', prompt: 'Bir etkinlik için flyer tasarla.' },
      { title: 'Marka Kimliği', prompt: 'Bir marka kimliği tasarımı oluştur.' },
      { title: 'UI Kit', prompt: 'Bir uygulama için UI kit tasarla.' },
      { title: 'İkon Seti', prompt: 'Bir proje için ikon seti oluştur.' },
      { title: 'Sosyal Medya Gönderisi', prompt: 'Sosyal medya için bir gönderi tasarla.' },
      { title: 'Bülten Başlığı', prompt: 'Bir bülten için başlık oluştur.' },
      { title: 'Sunum Slaytı', prompt: 'Bir sunum için slayt tasarla.' },
      { title: 'E-posta Şablonu', prompt: 'E-posta pazarlaması için bir şablon oluştur.' },
      { title: 'Broşür Tasarımı', prompt: 'Bir işletme için broşür tasarla.' },
      { title: 'Menü Tasarımı', prompt: 'Bir restoran menüsü için tasarım oluştur.' },
      { title: 'Kartvizit', prompt: 'Bir kartvizit tasarla.' },
      { title: 'Davetiye Kartı', prompt: 'Bir davetiye kartı tasarımı oluştur.' },
      { title: 'Takvim Tasarımı', prompt: 'Bir marka için takvim tasarla.' },
      { title: 'T-shirt Tasarımı', prompt: 'Bir T-shirt için tasarım oluştur.' },
      { title: 'Duvar Kağıdı Tasarımı', prompt: 'Cihazlar için duvar kağıdı tasarla.' },
      { title: 'Sticker Tasarımı', prompt: 'Sticker\'lar için bir tasarım oluştur.' },
      { title: 'Rozet Tasarımı', prompt: 'Bir etkinlik için rozet tasarla.' },
      { title: 'Sertifika Tasarımı', prompt: 'Bir sertifika için tasarım oluştur.' },
      { title: 'Etiket Tasarımı', prompt: 'Bir ürün için etiket tasarla.' },
      { title: 'Ambalaj Mockup\'ı', prompt: 'Ürün ambalajı için bir mockup oluştur.' },
      { title: 'Sosyal Medya Hikayesi', prompt: 'Sosyal medya için bir hikaye tasarla.' },
      { title: 'Profil Resmi', prompt: 'Bir profil resmi tasarımı oluştur.' },
      { title: 'Kapak Fotoğrafı', prompt: 'Sosyal medya için kapak fotoğrafı tasarla.' },
      { title: 'Poster Serisi', prompt: 'İlişkili bir poster serisi oluştur.' },
      { title: 'Karakter Sayfası', prompt: 'Animasyon için bir karakter sayfası tasarla.' },
      { title: 'Ortam Konsepti', prompt: 'Bir ortam için konsept oluştur.' },
      { title: 'Araç Tasarımı', prompt: 'Bir oyun için araç tasarla.' },
      { title: 'Yaratık Tasarımı', prompt: 'Bir yaratık için tasarım oluştur.' },
      { title: 'Silah Tasarımı', prompt: 'Bir oyun için silah tasarla.' },
      { title: 'Prop Tasarımı', prompt: 'Bir prop için tasarım oluştur.' },
      { title: 'Sahne Kompozisyonu', prompt: 'Bir sahne için kompozisyon tasarla.' },
      { title: 'Işıklandırma Kurulumu', prompt: 'Bir sahne için ışıklandırma kurulumu oluştur.' },
      { title: 'Renk Paleti', prompt: 'Bir proje için renk paleti tasarla.' },
      { title: 'Tipografi Tasarımı', prompt: 'Bir tipografi tasarımı oluştur.' },
      { title: 'Desen Tasarımı', prompt: 'Bir ürün için desen tasarla.' }
    ]
  },
  'Fooocus Colab': {
    en: [
      { title: 'Game Character Creation', prompt: 'Create a high-resolution game character concept art.' },
      { title: 'UI Design', prompt: 'Create a modern UI design for a mobile banking app.' },
      { title: 'Logo Design', prompt: 'Design a minimalist logo for a tech startup.' },
      { title: 'Scene Illustration', prompt: 'Illustrate a fantasy game scene with detailed background.' },
      { title: 'Icon Set', prompt: 'Create a consistent icon set for a productivity app.' },
      { title: 'Isometric Room', prompt: 'Create an isometric room for a simulation game.' },
      { title: 'App Splash Screen', prompt: 'Design a splash screen for a mobile app.' },
      { title: 'Mascot Character', prompt: 'Create a mascot for a children\'s brand.' },
      { title: 'Board Game Box', prompt: 'Design a box for a new board game.' },
      { title: 'Pixel Art Sprite', prompt: 'Create a pixel art sprite for a retro game.' },
      { title: 'Loading Animation', prompt: 'Create a loading animation for a web app.' },
      { title: 'Achievement Badge', prompt: 'Design an achievement badge for a gamified app.' },
      { title: 'Social Media Banner', prompt: 'Create a banner for a tech event.' },
      { title: 'NFT Artwork', prompt: 'Create an NFT artwork with a unique style.' },
      { title: 'Weather Icons', prompt: 'Design a weather icon set for a mobile app.' },
      { title: 'App Store Screenshots', prompt: 'Create screenshots for an app store listing.' },
      { title: 'Character Expression Sheet', prompt: 'Create a sheet showing different character emotions.' },
      { title: 'Game Map', prompt: 'Design a map for a fantasy RPG.' },
      { title: 'Card Game Illustration', prompt: 'Illustrate a card for a digital card game.' },
      { title: '3D Model Reference', prompt: 'Create a reference image for a 3D modeler.' },
      { title: 'Comic Panel', prompt: 'Create a comic panel for a webtoon.' },
      { title: 'Infographic', prompt: 'Design an infographic about a technology topic.' },
      { title: 'E-book Cover', prompt: 'Create a cover for a technical e-book.' },
      { title: 'App Icon', prompt: 'Design an app icon for a productivity tool.' },
      { title: 'Animated Sticker', prompt: 'Create an animated sticker for messaging apps.' },
      { title: 'Desktop Wallpaper', prompt: 'Create a tech-themed desktop wallpaper.' },
      { title: 'Product Mockup', prompt: 'Create a product mockup for a new device.' },
      { title: 'Landing Page Hero', prompt: 'Design a hero image for a landing page.' },
      { title: 'Team Avatar Set', prompt: 'Create avatars for a project team.' },
      { title: 'Event Poster', prompt: 'Design a poster for a hackathon.' },
      { title: 'Game UI Elements', prompt: 'Create UI elements for a mobile game.' },
      { title: 'Startup Pitch Deck Slide', prompt: 'Design a slide for a startup pitch deck.' },
      { title: 'Blog Illustration', prompt: 'Create an illustration for a technical blog post.' },
      { title: 'App Onboarding Screens', prompt: 'Design onboarding screens for an app.' },
      { title: 'Achievement Cup', prompt: 'Create a cup icon for a leaderboard.' },
      { title: 'VR Environment', prompt: 'Create a concept for a VR environment.' },
      { title: 'AR Marker', prompt: 'Design an AR marker for an educational app.' },
      { title: 'Merchandise Design', prompt: 'Create a T-shirt design for a tech conference.' },
      { title: 'Animated Logo', prompt: 'Create an animated version of a company logo.' },
      { title: 'App Notification Icon', prompt: 'Design a notification icon for a mobile app.' },
      { title: 'Game Power-up Icon', prompt: 'Create a power-up icon for a platform game.' },
      { title: 'Puzzle Game Tiles', prompt: 'Design tiles for a puzzle game.' },
      { title: 'Stream Overlay', prompt: 'Create a stream overlay for a gaming channel.' },
      { title: 'App Widget', prompt: 'Design a widget for a weather app.' },
      { title: 'Game Achievement Icon', prompt: 'Create an icon for a game achievement.' },
      { title: 'App Loading Screen', prompt: 'Design a creative loading screen for an app.' },
      { title: 'Social Media Profile Picture', prompt: 'Create a profile picture for a developer.' },
      { title: 'App Rating Stars', prompt: 'Design stars for an app rating system.' },
      { title: 'Game Inventory Icon', prompt: 'Create an inventory icon for an RPG.' },
      { title: 'App Tutorial Illustration', prompt: 'Create an illustration for an app tutorial.' }
    ],
    tr: [
      { title: 'Oyun Karakteri Oluştur', prompt: 'Yüksek çözünürlüklü bir oyun karakteri konsept sanatı oluştur.' },
      { title: 'UI Tasarımı', prompt: 'Mobil bankacılık uygulaması için modern bir UI tasarımı oluştur.' },
      { title: 'Logo Tasarımı', prompt: 'Bir teknoloji startup\'ı için minimalist bir logo tasarla.' },
      { title: 'Sahne İllüstrasyonu', prompt: 'Detaylı arka plana sahip fantastik bir oyun sahnesi illüstre et.' },
      { title: 'İkon Seti', prompt: 'Bir üretkenlik uygulaması için tutarlı bir ikon seti oluştur.' },
      { title: 'İzometrik Oda', prompt: 'Bir simülasyon oyunu için izometrik bir oda oluştur.' },
      { title: 'Uygulama Açılış Ekranı', prompt: 'Mobil uygulama için bir açılış ekranı tasarla.' },
      { title: 'Maskot Karakteri', prompt: 'Çocuk markası için bir maskot oluştur.' },
      { title: 'Kutu Oyunu Kutusu', prompt: 'Yeni bir kutu oyunu için kutu tasarımı yap.' },
      { title: 'Piksel Sanat Sprite', prompt: 'Retro oyun için bir piksel sanat sprite\'ı oluştur.' },
      { title: 'Yükleme Animasyonu', prompt: 'Web uygulaması için bir yükleme animasyonu oluştur.' },
      { title: 'Başarı Rozeti', prompt: 'Oyunlaştırılmış bir uygulama için başarı rozeti tasarla.' },
      { title: 'Sosyal Medya Banner', prompt: 'Teknoloji etkinliği için bir banner oluştur.' },
      { title: 'NFT Sanat Eseri', prompt: 'Benzersiz bir stile sahip NFT sanat eseri oluştur.' },
      { title: 'Hava Durumu İkonları', prompt: 'Mobil uygulama için hava durumu ikon seti tasarla.' },
      { title: 'Uygulama Mağazası Ekran Görüntüleri', prompt: 'Uygulama mağazası listesi için ekran görüntüleri oluştur.' },
      { title: 'Karakter İfade Sayfası', prompt: 'Farklı karakter duygularını gösteren bir sayfa oluştur.' },
      { title: 'Oyun Haritası', prompt: 'Fantastik bir RPG için harita tasarla.' },
      { title: 'Kart Oyunu İllüstrasyonu', prompt: 'Dijital kart oyunu için bir kart illüstre et.' },
      { title: '3D Model Referansı', prompt: '3D modelleyici için referans görsel oluştur.' },
      { title: 'Çizgi Roman Paneli', prompt: 'Webtoon için bir çizgi roman paneli oluştur.' },
      { title: 'İnfografik', prompt: 'Teknoloji konusu için bir infografik tasarla.' },
      { title: 'E-kitap Kapağı', prompt: 'Teknik bir e-kitap için kapak oluştur.' },
      { title: 'Uygulama İkonu', prompt: 'Üretkenlik aracı için bir uygulama ikonu tasarla.' },
      { title: 'Animasyonlu Sticker', prompt: 'Mesajlaşma uygulamaları için animasyonlu bir sticker oluştur.' },
      { title: 'Masaüstü Duvar Kağıdı', prompt: 'Teknoloji temalı bir masaüstü duvar kağıdı oluştur.' },
      { title: 'Ürün Mockup', prompt: 'Yeni bir cihaz için ürün mockup\'ı oluştur.' },
      { title: 'Landing Page Hero', prompt: 'Bir landing page için hero görseli tasarla.' },
      { title: 'Takım Avatar Seti', prompt: 'Proje takımı için avatarlar oluştur.' },
      { title: 'Etkinlik Posteri', prompt: 'Bir hackathon için poster tasarla.' },
      { title: 'Oyun UI Elementleri', prompt: 'Mobil oyun için UI elementleri oluştur.' },
      { title: 'Startup Pitch Deck Slaytı', prompt: 'Startup pitch deck\'i için bir slayt tasarla.' },
      { title: 'Blog İllüstrasyonu', prompt: 'Teknik blog yazısı için bir illüstrasyon oluştur.' },
      { title: 'Uygulama Tanıtım Ekranları', prompt: 'Onboarding için tanıtım ekranları tasarla.' },
      { title: 'Başarı Kupası', prompt: 'Liderlik tablosu için bir kupa ikonu oluştur.' },
      { title: 'VR Ortamı', prompt: 'VR ortamı için bir konsept oluştur.' },
      { title: 'AR İşaretçisi', prompt: 'Eğitim uygulaması için bir AR işaretçisi tasarla.' },
      { title: 'Merchandise Tasarımı', prompt: 'Teknoloji konferansı için T-shirt tasarımı oluştur.' },
      { title: 'Animasyonlu Logo', prompt: 'Şirket logosunun animasyonlu versiyonunu oluştur.' },
      { title: 'Uygulama Bildirim İkonu', prompt: 'Mobil uygulama için bildirim ikonu tasarla.' },
      { title: 'Oyun Güçlendirme İkonu', prompt: 'Platform oyunu için güçlendirme ikonu oluştur.' },
      { title: 'Bulmaca Oyunu Karoları', prompt: 'Bulmaca oyunu için karolar tasarla.' },
      { title: 'Yayın Overlay', prompt: 'Oyun kanalı için yayın overlay\'i oluştur.' },
      { title: 'Uygulama Widget\'ı', prompt: 'Hava durumu uygulaması için widget tasarla.' },
      { title: 'Oyun Başarı İkonu', prompt: 'Oyun başarısı için bir ikon oluştur.' },
      { title: 'Uygulama Yükleme Ekranı', prompt: 'Uygulama için yaratıcı bir yükleme ekranı tasarla.' },
      { title: 'Sosyal Medya Profil Resmi', prompt: 'Geliştirici için bir profil resmi oluştur.' },
      { title: 'Uygulama Değerlendirme Yıldızları', prompt: 'Uygulama değerlendirme sistemi için yıldızlar tasarla.' },
      { title: 'Oyun Envanter İkonu', prompt: 'RPG için bir envanter ikonu oluştur.' },
      { title: 'Uygulama Öğretici İllüstrasyonu', prompt: 'Uygulama öğreticisi için bir illüstrasyon oluştur.' }
    ]
  },
  'Copilot': {
    en: [
      { title: 'Function Auto-Completion', prompt: 'Auto-complete this function based on its signature and comments.' },
      { title: 'Unit Test Suggestion', prompt: 'Generate unit tests for the following function.' },
      { title: 'Algorithm Optimization', prompt: 'Optimize this algorithm for better performance.' },
      { title: 'Code Completion', prompt: 'Auto-complete the following function and add its documentation.' },
      { title: 'Refactor and Explain', prompt: 'Refactor the code for better readability and maintainability, and explain the changes.' },
      { title: 'Performance Improvement', prompt: 'Suggest improvements to enhance the code\'s performance and update if necessary.' },
      { title: 'Error Detection and Fix', prompt: 'Find and fix potential errors in the code.' },
      { title: 'Add Comments', prompt: 'Add explanatory comments to important parts of the code.' },
      { title: 'Write Test Function', prompt: 'Write a unit test for the following function.' },
      { title: 'API Integration', prompt: 'Complete the code to integrate with the given API.' },
      { title: 'Data Validation', prompt: 'Add code to validate user input data.' },
      { title: 'Generate Documentation', prompt: 'Write a brief documentation explaining how the code works.' },
      { title: 'Create Code Template', prompt: 'Create a reusable code template for the specified functionality.' },
      { title: 'State Management', prompt: 'Implement state management for this React component using Redux/Context.' },
      { title: 'Form Validation', prompt: 'Add form validation logic with error messages and success states.' },
      { title: 'API Error Handling', prompt: 'Implement comprehensive error handling for API calls.' },
      { title: 'Authentication Flow', prompt: 'Implement JWT authentication flow with refresh tokens.' },
      { title: 'Data Fetching', prompt: 'Implement data fetching with loading and error states.' },
      { title: 'File Upload', prompt: 'Create a file upload component with progress tracking.' },
      { title: 'Search Implementation', prompt: 'Implement search functionality with debouncing.' },
      { title: 'Pagination Logic', prompt: 'Add pagination logic for a list of items.' },
      { title: 'Sorting Function', prompt: 'Implement sorting functionality for a data table.' },
      { title: 'Filter Implementation', prompt: 'Add filtering logic for a list of items.' },
      { title: 'Export Function', prompt: 'Create an export function for data in various formats.' },
      { title: 'Import Function', prompt: 'Implement data import functionality with validation.' },
      { title: 'Cache Implementation', prompt: 'Add caching logic for API responses.' },
      { title: 'WebSocket Integration', prompt: 'Implement real-time updates using WebSocket.' },
      { title: 'PDF Generation', prompt: 'Create a function to generate PDF documents.' },
      { title: 'Email Template', prompt: 'Create an HTML email template with responsive design.' },
      { title: 'Notification System', prompt: 'Implement a notification system with different types.' },
      { title: 'Data Visualization', prompt: 'Create data visualization components using charts.' },
      { title: 'Drag and Drop', prompt: 'Implement drag and drop functionality for items.' },
      { title: 'Infinite Scroll', prompt: 'Add infinite scroll functionality to a list.' },
      { title: 'Image Processing', prompt: 'Implement image processing and optimization.' },
      { title: 'Video Player', prompt: 'Create a custom video player with controls.' },
      { title: 'Audio Processing', prompt: 'Implement audio processing functionality.' },
      { title: 'Map Integration', prompt: 'Add map integration with markers and routes.' },
      { title: 'Calendar Component', prompt: 'Create a calendar component with events.' },
      { title: 'Rich Text Editor', prompt: 'Implement a rich text editor with formatting.' },
      { title: 'Code Editor', prompt: 'Create a code editor with syntax highlighting.' },
      { title: 'File System', prompt: 'Implement file system operations with permissions.' },
      { title: 'Database Migration', prompt: 'Create database migration scripts.' },
      { title: 'API Documentation', prompt: 'Generate API documentation with examples.' },
      { title: 'Performance Monitoring', prompt: 'Implement performance monitoring and logging.' },
      { title: 'Security Measures', prompt: 'Add security measures and input sanitization.' },
      { title: 'Accessibility', prompt: 'Implement accessibility features and ARIA labels.' },
      { title: 'Internationalization', prompt: 'Add internationalization support.' },
      { title: 'Theme System', prompt: 'Create a theme system with dark/light modes.' },
      { title: 'Responsive Design', prompt: 'Implement responsive design patterns.' },
      { title: 'Animation System', prompt: 'Create an animation system with transitions.' }
    ],
    tr: [
      { title: 'Fonksiyon Otomatik Tamamlama', prompt: 'Fonksiyonun imzası ve açıklamasına göre otomatik tamamla.' },
      { title: 'Birim Test Önerisi', prompt: 'Aşağıdaki fonksiyon için birim testler oluştur.' },
      { title: 'Algoritma Optimizasyonu', prompt: 'Bu algoritmayı daha iyi performans için optimize et.' },
      { title: 'Kod Tamamlama', prompt: 'Aşağıdaki fonksiyonu otomatik olarak tamamla ve açıklamasını ekle.' },
      { title: 'Refaktör ve Açıkla', prompt: 'Kodun daha okunabilir ve sürdürülebilir olması için refaktör et ve yapılan değişiklikleri açıkla.' },
      { title: 'Performans İyileştirme', prompt: 'Kodun performansını artırmak için önerilerde bulun ve gerekirse kodu güncelle.' },
      { title: 'Hata Tespiti ve Düzeltme', prompt: 'Kodda olası hataları bul ve düzelt.' },
      { title: 'Yorum Satırı Ekle', prompt: 'Kodun önemli noktalarına açıklayıcı yorum satırları ekle.' },
      { title: 'Test Fonksiyonu Yaz', prompt: 'Aşağıdaki fonksiyon için birim testi yaz.' },
      { title: 'API Entegrasyonu', prompt: 'Aşağıdaki kodu verilen API ile entegre edecek şekilde tamamla.' },
      { title: 'Veri Doğrulama', prompt: 'Kullanıcıdan alınan verinin doğruluğunu kontrol eden kodu ekle.' },
      { title: 'Dökümantasyon Oluştur', prompt: 'Kodun nasıl çalıştığını açıklayan kısa bir dökümantasyon yaz.' },
      { title: 'Kod Şablonu Oluştur', prompt: 'Belirtilen işlev için tekrar kullanılabilir bir kod şablonu oluştur.' },
      { title: 'Durum Yönetimi', prompt: 'Bu React bileşeni için Redux/Context kullanarak durum yönetimi uygula.' },
      { title: 'Form Doğrulama', prompt: 'Hata mesajları ve başarı durumları ile form doğrulama mantığı ekle.' },
      { title: 'API Hata Yönetimi', prompt: 'API çağrıları için kapsamlı hata yönetimi uygula.' },
      { title: 'Kimlik Doğrulama Akışı', prompt: 'Yenileme tokenları ile JWT kimlik doğrulama akışı uygula.' },
      { title: 'Veri Çekme', prompt: 'Yükleme ve hata durumları ile veri çekme işlemini uygula.' },
      { title: 'Dosya Yükleme', prompt: 'İlerleme takibi ile dosya yükleme bileşeni oluştur.' },
      { title: 'Arama Uygulaması', prompt: 'Debouncing ile arama işlevselliği uygula.' },
      { title: 'Sayfalama Mantığı', prompt: 'Öğe listesi için sayfalama mantığı ekle.' },
      { title: 'Sıralama Fonksiyonu', prompt: 'Veri tablosu için sıralama işlevselliği uygula.' },
      { title: 'Filtre Uygulaması', prompt: 'Öğe listesi için filtreleme mantığı ekle.' },
      { title: 'Dışa Aktarma Fonksiyonu', prompt: 'Verileri çeşitli formatlarda dışa aktarma fonksiyonu oluştur.' },
      { title: 'İçe Aktarma Fonksiyonu', prompt: 'Doğrulama ile veri içe aktarma işlevselliği uygula.' },
      { title: 'Önbellek Uygulaması', prompt: 'API yanıtları için önbellek mantığı ekle.' },
      { title: 'WebSocket Entegrasyonu', prompt: 'WebSocket kullanarak gerçek zamanlı güncellemeler uygula.' },
      { title: 'PDF Oluşturma', prompt: 'PDF belgeleri oluşturmak için bir fonksiyon oluştur.' },
      { title: 'E-posta Şablonu', prompt: 'Duyarlı tasarıma sahip HTML e-posta şablonu oluştur.' },
      { title: 'Bildirim Sistemi', prompt: 'Farklı türlerde bildirim sistemi uygula.' },
      { title: 'Veri Görselleştirme', prompt: 'Grafikler kullanarak veri görselleştirme bileşenleri oluştur.' },
      { title: 'Sürükle ve Bırak', prompt: 'Öğeler için sürükle ve bırak işlevselliği uygula.' },
      { title: 'Sonsuz Kaydırma', prompt: 'Listeye sonsuz kaydırma işlevselliği ekle.' },
      { title: 'Görüntü İşleme', prompt: 'Görüntü işleme ve optimizasyonu uygula.' },
      { title: 'Video Oynatıcı', prompt: 'Kontrollerle özel bir video oynatıcı oluştur.' },
      { title: 'Ses İşleme', prompt: 'Ses işleme işlevselliği uygula.' },
      { title: 'Harita Entegrasyonu', prompt: 'İşaretçiler ve rotalarla harita entegrasyonu ekle.' },
      { title: 'Takvim Bileşeni', prompt: 'Olaylarla bir takvim bileşeni oluştur.' },
      { title: 'Zengin Metin Editörü', prompt: 'Biçimlendirme ile zengin metin editörü uygula.' },
      { title: 'Kod Editörü', prompt: 'Sözdizimi vurgulama ile kod editörü oluştur.' },
      { title: 'Dosya Sistemi', prompt: 'İzinlerle dosya sistemi işlemlerini uygula.' },
      { title: 'Veritabanı Geçişi', prompt: 'Veritabanı geçiş betikleri oluştur.' },
      { title: 'API Dokümantasyonu', prompt: 'Örneklerle API dokümantasyonu oluştur.' },
      { title: 'Performans İzleme', prompt: 'Performans izleme ve günlük kaydı uygula.' },
      { title: 'Güvenlik Önlemleri', prompt: 'Güvenlik önlemleri ve girdi temizleme ekle.' },
      { title: 'Erişilebilirlik', prompt: 'Erişilebilirlik özellikleri ve ARIA etiketleri uygula.' },
      { title: 'Uluslararasılaştırma', prompt: 'Uluslararasılaştırma desteği ekle.' },
      { title: 'Tema Sistemi', prompt: 'Karanlık/aydınlık modları ile tema sistemi oluştur.' },
      { title: 'Duyarlı Tasarım', prompt: 'Duyarlı tasarım desenlerini uygula.' },
      { title: 'Animasyon Sistemi', prompt: 'Geçişlerle bir animasyon sistemi oluştur.' }
    ]
  }
}; 